nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173',  '*']  
        allow_headers: ['Content-Type', 'Authorization', '*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']  
        expose_headers: []  # Expose des en-têtes spécifiques si nécessaire
        max_age: 3600  # Cache des réponses OPTIONS pendant 1 heure

    # # Si tu veux restreindre certaines routes, tu peux spécifier des règles spécifiques
    # paths:
    #     '^/api/': # Appliquer ces règles aux routes API
    #         allow_origin: ['http://localhost:5173']
    #         allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    #         allow_headers: ['Content-Type', 'Authorization']
    #         max_age: 3600
