security:

    # Paramètres de hashage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseur d'utilisateurs
    providers:
        # Utilisation de la base de données pour récupérer les utilisateurs
        # Change cette section pour ta base de données (entité User)
        database_users:
            entity:
                class: App\Entity\User
                property: email  # Le champ unique qui identifie l'utilisateur (souvent l'email)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # Utilisation de la session pour gérer les connexions
            lazy: true
            provider: database_users

            # Formulaire de connexion
            form_login:
                login_path: login
                check_path: login
                default_target_path: /dashboard  # Page de redirection après une connexion réussie

            # Déconnexion
            logout:
                path: logout
                target: /login  # Rediriger vers la page de login après la déconnexion

    # Contrôle d'accès
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
